all: arvcameratest

CFLAGS += -I/dls_sw/work/common/glibnew/lib/glib-2.0/include
CFLAGS += -I/dls_sw/work/common/glibnew/include/glib-2.0
CFLAGS += -I/home/jr76/tools/aravis/include/aravis

LDLIBS += -lglib-2.0
LDLIBS += -laravis
LDFLAGS += -Wl,-rpath=/dls_sw/work/common/glibnew/lib -L=/dls_sw/work/common/glibnew/lib
LDFLAGS += -Wl,-rpath=/home/jr76/tools/aravis/lib -L=/home/jr76/tools/aravis/lib

